# Generated by Django 3.1.2 on 2020-12-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_estacionamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamentos',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
