# Generated by Django 3.1.2 on 2020-12-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_estacionamentos_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamentos',
            name='valor',
            field=models.FloatField(default=15.0),
        ),
        migrations.AlterField(
            model_name='estacionamentos',
            name='foto',
            field=models.ImageField(upload_to='estacionamento'),
        ),
    ]
